### ISSUE TITLE
Logo Implementation TODO 

### ISSUE THREAD

**Issue by Toyz** [CodingTrain/Logo#37]
Below is a list of things that still need to be implemented into the parser for the logo language:

- [ ] circle > `circle radius extend steps`
- [ ] dot > `dot radius`
- [x] pensize > `pensize strokeSize`
- [ ] pencolor > `pencolor color`
- [ ] fillcolor > `fillcolor color` _note_: this is dealing with custom shapes which we currently don't support yet
- [ ] fill > `fill true/false` _note_: uses fillcolor to fill the shape if true
- [ ] begin_fill > start shape
- [ ] end_fill > end shape
- [ ] write > `write text` _note_: this writes to the canvas as text ex "hello world"

Things to implement in turtle to add more features:
- [ ] Dynamic stroke size so we can change it with pensize
- [ ] Ability to create shapes and ill them with a solid color

--

Note: In Logo `color` sets both `fillcolor` and `pencolor`, this means we don't actually implement `color` properly yet

**Comment by shiffman** [comment]
Is this up to date?

**Comment by Toyz** [comment]
Yes this is currently up to date, we still have things we need to implement that are in this list

Sent from my iPhone

On Nov 13, 2018, at 6:35 AM, Daniel Shiffman <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this up to date?

**Comment by NiclasTheSquirrel** [comment]
Circle mode center or corner`??

**Comment by TheTastefulToastie** [comment]
@Toyz Hi for #75  do you know where the `circle` command is documented?
Looking in the Berkeley Logo Manual I can only find the `ARC` command:
```
ARC angle radius

	draws an arc of a circle, with the turtle at the center, with the
	specified radius, starting at the turtle's heading and extending
	clockwise through the specified angle.  The turtle does not move.
```
Should we implement a `circle` command because it's intuitive? or just support Berkeley Logo (which has only `ARK` or both?

**Comment by NiclasTheSquirrel** [comment]
For color, should it be rgb, or should it be like this:
command 51 (rgb: 51,51,51)

**Comment by Toyz** [comment]
Circle could he a shortcut to arc

**Comment by Toyz** [comment]
And we could change the color command to support rgb instead of having a colorrgb function

**Comment by NiclasTheSquirrel** [comment]
So we should replace the color command with colorRGB or just make it support both hex and RGB?
